apiVersion: apps/v1
kind: Deployment
metadata:
  name: day4-hello-app-1-deployment
  labels:
    app: hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: sec-ctx-demo-2
        image: gcr.io/google-samples/hello-app:2.0
        securityContext:
          runAsUser: 2000
          allowPrivilegeEscalation: false