apiVersion: apps/v1
kind: Deployment
metadata:
  name: day4-nginx-1-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80