apiVersion: apps/v1
kind: Deployment
metadata:
  name: day2-nginx-1
  labels:
    app: nginx
spec:  
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: nginx