apiVersion: apps/v1
kind: Deployment
metadata:
  name: day2-nginx-2-5
  labels:
    app: nginx
spec:  
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1    # Number of extra pods to create during update
        maxUnavailable: 1  # Number of pods that can be unavailable during update
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
      tolerations:
      - key: "size"
        operator: "Equal"
        value: "Large"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: size
                operator: In
                values:
                - Large
  replicas: 2
  selector:
    matchLabels:
      app: nginx