apiVersion: apps/v1
kind: Deployment
metadata:
  name: day2-nginx-2-2
  labels:
    app: nginx
spec:  
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1    # Number of extra pods to create during update
        maxUnavailable: 1  # Number of pods that can be unavailable during update
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
      nodeSelector: 
        size: Large # Assign the pod to a specific node based on the label - Node Selector. Use this -> kubectl label node <node-name> size=Large
  replicas: 2
  selector:
    matchLabels:
      app: nginx