name: Deploy to Pod - Day1

on:
  push:
    branches:
      - day1

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List current directory
      run: pwd

    - name: List contents of the repository
      run: ls -R
      
    - name: Apply Pod configuration
      run: kubectl apply -f /pods/nginx-pod.yaml